# Datasets

In [106]:
library(datasets)
data(airquality)
head(airquality)
cov(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

Ozone Solar.R Wind        Temp       Month      Day        
Ozone   NA    NA               NA         NA         NA          NA
Solar.R NA    NA               NA         NA         NA          NA
Wind    NA    NA       12.4115385 -15.272136 -0.8897532   0.8488519
Temp    NA    NA      -15.2721362  89.591331  5.6439628 -10.9574303
Month   NA    NA       -0.8897532   5.643963  2.0065359  -0.0999742
Day     NA    NA        0.8488519 -10.957430 -0.0999742  78.5797214

# Data Types - Part 1

In [4]:
x <- 1
print(x)
1 -> x
print(x)
x
msg <- "hello"
msg

[1] 1
[1] 1


[1] 1

[1] "hello"

In [6]:
x <- 1:5
x
print(x)

[1] 1 2 3 4 5

[1] 1 2 3 4 5


# Data Types - Part 2

In [7]:
x <- c(0.5, 0.6)      # numeric
x
x <- c(TRUE, FALSE)   # logical
x
x <- c(T, F)          # logical
x
x <- c("a", "6", "c") # character
x
x <- c(9:29)          # integer
x
x <- c(1+0i, 2+4i)    # complex
x

[1] 0.5 0.6

[1]  TRUE FALSE

[1]  TRUE FALSE

[1] "a" "6" "c"

[1]  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29

[1] 1+0i 2+4i

In [8]:
x <- vector("numeric", length = 10)
x

[1] 0 0 0 0 0 0 0 0 0 0

In [12]:
y <- c(1.7, "a") # character, 1.7 is converted into "1.7"
y
y <- c(TRUE, 2,"a") # character, TRUE is converted into "TRUE"
y
y <- c("a", TRUE) # character, TRUE is converted to "TRUE"
y

[1] "1.7" "a"

[1] "TRUE" "2"    "a"

[1] "a"    "TRUE"

In [15]:
x <- -3:6
class(x)
as.numeric(x)
as.logical(x)
as.character(x)
x

[1] "integer"

[1] -3 -2 -1  0  1  2  3  4  5  6

[1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1] "-3" "-2" "-1" "0"  "1"  "2"  "3"  "4"  "5"  "6"

[1] -3 -2 -1  0  1  2  3  4  5  6

In [17]:
x <-c("9", "978L", "2+0.5i")
x
as.complex(x)

[1] "9"      "978L"   "2+0.5i"

Warning message:
“NAs introduced by coercion”


[1] 9+0.0i     NA 2+0.5i

In [18]:
x<-"True"
as.logical(x)
as.complex(x)

[1] TRUE

Warning message:
“NAs introduced by coercion”


[1] NA

In [21]:
m <- matrix(nrow=2, ncol=3)
m
dim(m)
attributes(m)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[1] 2 3

$dim
[1] 2 3

In [22]:
m <- matrix(1:6, ncol = 3, nrow = 2)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [23]:
m <- 1:10
m
dim(m) <- c(2, 5)
m

[1]  1  2  3  4  5  6  7  8  9 10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [24]:
x <- 1:3
y <- c("a","b","c")
cbind(x, y)
rbind(x, x)

x y
[1,] 1 a
[2,] 2 b
[3,] 3 c

[,1] [,2] [,3]
x 1    2    3   
x 1    2    3

In [25]:
x <- list(1, c("a","b"), TRUE, 1 + 4i,m)
x

[[1]]
[1] 1

[[2]]
[1] "a" "b"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

[[5]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

# Data Types - Part 3

In [26]:
x <- factor(c("yes", "yes", "no", "yes", "no"))
x

[1] yes yes no  yes no 
Levels: no yes

In [27]:
table(x)

x
 no yes 
  2   3 

In [28]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [31]:
x <- factor(c("yes", "yes", "no", "yes", "no"),levels = c("yes", "no"))
x

[1] yes yes no  yes no 
Levels: yes no

# Missing values

In [35]:
x <- c(1, 2, NA, 10, 3)
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [36]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [37]:
x <- c(1, 2, NaN, NA, 4)
is.na(x)

[1] FALSE FALSE  TRUE  TRUE FALSE

In [38]:
is.nan(x)

[1] FALSE FALSE  TRUE FALSE FALSE

# DataFrames

In [39]:
x <- data.frame(foo = 1:4, bar = c(T,T,F,F))
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [40]:
nrow(x)
ncol(x)

[1] 4

[1] 2

In [41]:
x <- 1:3
names(x)

NULL

In [42]:
names(x) <- c("foo", "bar", "norf")
x

foo  bar norf 
   1    2    3

In [43]:
names(x)

[1] "foo"  "bar"  "norf"

In [44]:
x <- list(a = 1, b = 2, c = 3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [45]:
m <- matrix(1:4, nrow = 2, ncol = 2)
dimnames(m) <- list(c("a", "b"), c("c", "d"))
m

c d
a 1 3
b 2 4

# Subsetting - Part 1

In [46]:
x<- c("a", "b", "c", "c", "d", "a")
x[1]

[1] "a"

In [47]:
x[2]

[1] "b"

In [48]:
x[1:4]

[1] "a" "b" "c" "c"

In [49]:
u <- x > "a"
u

[1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE

In [50]:
x[u]

[1] "b" "c" "c" "d"

In [51]:
x <- matrix(1:6, 2, 3)
x
x[1, c(3,2)]

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 5 3

In [52]:
x[2, 1]

[1] 2

In [53]:
x[1, ]

[1] 1 3 5

In [54]:
x[ ,2]

[1] 3 4

In [55]:
x <- matrix(1:6, 2, 3)
x[1, 2]

[1] 3

In [56]:
x[1, 2,drop=FALSE]

[,1]
[1,] 3

In [57]:
x <- matrix(1:6, 2, 3)
x[1, ]

[1] 1 3 5

In [58]:
x <- matrix(1:6, 2, 3)
x[1, ,drop=FALSE]

[,1] [,2] [,3]
[1,] 1    3    5

In [59]:
x <- list(foo = 1:4, bar = 0.6)
x[1]

$foo
[1] 1 2 3 4

In [60]:
x[[1]]

[1] 1 2 3 4

In [70]:
x$foo
x["foo"]

[1] 1 2 3 4

$foo
[1] 1 2 3 4

In [65]:
x["bar"]

$bar
[1] 0.6

In [67]:
x <-list(foo = 1:4, bar = 0.6, baz = "hello")
x[c(1, 3)]

$foo
[1] 1 2 3 4

$baz
[1] "hello"

In [68]:
x <- list(foo = 1:4, bar = 0.6, baz = "hello")
name <- "foo"
x[[name]]
x[["foo"]] # computed index for 'foo'
x$name # element 'name' doesn't exist
x$foo

[1] 1 2 3 4

[1] 1 2 3 4

NULL

[1] 1 2 3 4

In [77]:
x <-list(a = list(10, 12, 14), b = c(3.14, 2.81))
x[[c(1, 3)]]
x[[c(2, 1)]]

[1] 14

[1] 3.14

In [81]:
x[[1]][[3]]

[1] 14

# Partial Matching

In [82]:
x <- list(aardvark = 1.5,eraaaaaa=90)
x$ak

NULL

In [83]:
x[["a"]]

NULL

In [84]:
x[["a",exact=FALSE]]

[1] 1.5

# Removing NA values

In [88]:
x <- c(1, 2, NA, 4, NA, 5)
bad <- is.na(x)
x <- x[!bad]
x

[1] 1 2 4 5

In [89]:
x <- c(1, 2, 6, 4, NA, 5)
y <- c("a", "b", NA, "d", NA, "f")
good <- complete.cases(x, y)
good

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

In [91]:
x[good]
y[good]

[1] 1 2 4 5

[1] "a" "b" "d" "f"

In [92]:
#your_data= read.csv('your_data.csv')
#good <- complete.cases(your_data)
#your_data[good,]

In [97]:
seq(from=1,to=10)

seq(-1,-10)

seq(5.5,8)

seq(from=1,to=30,by=3)

seq(1,30,2)

seq.int(from=1,to=30, length.out=5)

y<-c(1,5,15,20)
seq(10,30,along.with = y)

seq_len(10)	#argument must be positive

[1]  1  2  3  4  5  6  7  8  9 10

[1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

[1] 5.5 6.5 7.5

[1]  1  4  7 10 13 16 19 22 25 28

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29

[1]  1.00  8.25 15.50 22.75 30.00

[1] 10.00000 16.66667 23.33333 30.00000

[1]  1  2  3  4  5  6  7  8  9 10