# **Apply**: Looping on the command line

-   lapply(): Loop over a list and evaluate and function on each element
-   sapply(): Same as lapply() but try to simplify the result
-   apply(): Apply a function over the margins of an array
-   tapply(): Apply a function over subsets of a vector
-   mapply(): Multivariate version of lapply

# lapply()

In [1]:
x <- list(a = 1:5, b = rnorm(10))
lapply(x, mean)

$a
[1] 3

$b
[1] -0.0910422

In [2]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))
lapply(x, mean)

$a
[1] 2.5

$b
[1] -0.2335122

$c
[1] 0.836663

$d
[1] 5.002462

In [6]:
x <- 1:4
lapply(x, runif)

[[1]]
[1] 0.7346971

[[2]]
[1] 0.7069235 0.9620357

[[3]]
[1] 0.3070496 0.9229005 0.3627234

[[4]]
[1] 0.8276282 0.7927837 0.5603835 0.1240166

In [7]:
x <- 1:4
lapply(x, runif, min = 0, max = 10)

[[1]]
[1] 8.115337

[[2]]
[1] 1.977081 9.480558

[[3]]
[1] 4.990966 5.948711 5.941629

[[4]]
[1] 2.500514 3.192105 8.793865 5.282904

In [8]:
x <- list(a = matrix(1:4, 2, 2), b = matrix(1:6, 3, 2))
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [9]:
lapply(x, function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

# sapply()

In [11]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))
sapply(x, mean)

a          b          c          d 
2.50000000 0.04972419 0.99883233 4.91394525

In [14]:
str(apply)

function (X, MARGIN, FUN, ..., simplify = TRUE)  


1 : rowwise

2 : colwise

In [16]:
x <- matrix(rnorm(200), 20, 10)
apply(x, 1, sum)   #rowSums
apply(x, 2, mean)  #colMeans

[1]  1.84482150 -3.10777564 -0.58352179 -3.88498417  2.03911238 -0.38856367
 [7] -0.09268114  0.34181820  9.14329800 -3.62438125  1.38439941  0.44695540
[13]  2.30361015  7.88463288 -0.61187785  1.70839022 -1.42360769  2.62353694
[19] -0.93645332 -1.40708891

[1]  0.27484305  0.03459575  0.40479470 -0.01200019  0.55590940 -0.10643274
 [7] -0.10376391 -0.16919195  0.02840779 -0.22417991

In [17]:
x <- matrix(rnorm(200), 20, 10)
apply(x, 1, quantile, probs = c(0.25, 0.75))

[,1]       [,2]      [,3]        [,4]       [,5]       [,6]      
25% -1.0026197 0.2212035 -0.78531989 -0.6949228 -1.4020226 -1.1815717
75%  0.1201862 0.8543376  0.01872764  0.9967704 -0.4180892  0.2726168
    [,7]       [,8]       [,9]       [,10]      [,11]      [,12]     
25% -0.8418331 -0.8871996 -0.1289502 -1.1106360 -1.1634183 -1.0287939
75%  0.8448166  0.3088824  0.1763737  0.2773667  0.8764587  0.7785223
    [,13]      [,14]      [,15]      [,16]      [,17]      [,18]     
25% -0.6725650 -0.9229873 -0.6953154 -0.2278993 -0.5287917 -0.4541874
75%  0.5018576 -0.2233608  0.9938846  0.4943931  0.6044566  0.8698024
    [,19]      [,20]     
25% -0.3858306 -0.8526098
75%  0.1687056  0.4544548

In [29]:
a <- array(rnorm(2 * 2 * 10), c(2, 2, 10))
apply(a, c(1, 2), mean) #keep the dimensions (1,2) : (2,2)
# rowMeans(a, dims = 2) same as above statement and keep first 2 dimentions (1,2) : (2,2)

[,1]        [,2]      
[1,] -0.08967845 -0.1446001
[2,]  0.30910713  0.3523174

# tapply()

In [30]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE)  


In [33]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(6, 5)  # generate 6 levels of 5 each
f
tapply(x, f, mean) # apply to each level

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6
Levels: 1 2 3 4 5 6

1          2          3          4          5          6 
-0.2961563  0.2421665  0.3760028  0.5471504  1.1895009  0.5182530

In [34]:
tapply(x, f, mean, simplify = FALSE)

$`1`
[1] -0.2961563

$`2`
[1] 0.2421665

$`3`
[1] 0.3760028

$`4`
[1] 0.5471504

$`5`
[1] 1.189501

$`6`
[1] 0.518253

In [35]:
tapply(x, f, range)

$`1`
[1] -1.0970269  0.3348383

$`2`
[1] -1.688696  1.341219

$`3`
[1] 0.1534361 0.5862209

$`4`
[1] 0.05062457 0.93820595

$`5`
[1] -0.3480515  2.4603199

$`6`
[1] -0.6847217  1.9645864

# split()

In [36]:
str(split)

function (x, f, drop = FALSE, ...)  


In [37]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10)
split(x, f)

$`1`
 [1]  1.769432042 -0.007039756 -0.416341175  0.367756925 -1.231860806
 [6] -0.388329921  2.059949951 -0.038007200 -0.168274160  0.445239369

$`2`
 [1] 0.7633481 0.0875368 0.1044498 0.1595779 0.2350366 0.0704085 0.5703718
 [8] 0.1100339 0.4275427 0.7163002

$`3`
 [1] -0.49761798  1.06014244  2.02755648  0.90684199  1.67362738  1.59379644
 [7]  2.71226813  0.92782637  2.19196464  0.03482819

In [38]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10)
lapply(split(x, f), mean)

$`1`
[1] 0.597626

$`2`
[1] 0.4399478

$`3`
[1] 0.9095019

# Splitting a Data Frame

In [39]:
library(datasets)
head(airquality)
s <- split(airquality, airquality$Month)
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [40]:
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

In [41]:
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm  = TRUE))

5         6         7          8          9        
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

In [42]:
x <- rnorm(10)
f1 <- gl(2, 5)
f2 <- gl(5, 2)
f1
f2
split(x, list(f1, f2))

[1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

[1] 1 1 2 2 3 3 4 4 5 5
Levels: 1 2 3 4 5

$`1.1`
[1] -1.8369384 -0.2442012

$`2.1`
numeric(0)

$`1.2`
[1] -0.7224304  0.7209571

$`2.2`
numeric(0)

$`1.3`
[1] -1.001823

$`2.3`
[1] -1.395187

$`1.4`
numeric(0)

$`2.4`
[1]  1.9469512 -0.4783816

$`1.5`
numeric(0)

$`2.5`
[1] -0.02868881  0.05445319

In [43]:
str(split(x, list(f1, f2)))

List of 10
 $ 1.1: num [1:2] -1.837 -0.244
 $ 2.1: num(0) 
 $ 1.2: num [1:2] -0.722 0.721
 $ 2.2: num(0) 
 $ 1.3: num -1
 $ 2.3: num -1.4
 $ 1.4: num(0) 
 $ 2.4: num [1:2] 1.947 -0.478
 $ 1.5: num(0) 
 $ 2.5: num [1:2] -0.0287 0.0545


In [45]:
str(split(x, list(f1, f2),drop=TRUE))

List of 6
 $ 1.1: num [1:2] -1.837 -0.244
 $ 1.2: num [1:2] -0.722 0.721
 $ 1.3: num -1
 $ 2.3: num -1.4
 $ 2.4: num [1:2] 1.947 -0.478
 $ 2.5: num [1:2] -0.0287 0.0545


# mapply()

In [46]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


In [47]:
list(rep(1, 4), rep(2, 3), rep(3, 2), rep(4, 1))

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [48]:
mapply(rep, 1:4, 4:1) # same as above

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

Vectorizing a function

In [54]:
noise <- function(n, mean, sd) {
  rnorm(n, mean, sd)
}
noise(5, 1, 2)
noise(1:5, 1:5, 2) # not work as expected

[1]  3.0758824  3.8580134 -2.8069798 -0.8727781 -2.4453496

[1]  1.684175 -1.347746  1.001654  0.480182  5.334605

In [56]:
mapply(noise, 1:5, 1:5, 2)
# list(noise(1, 1, 2), noise(2, 2, 2), noise(3, 3, 2), noise(4, 4, 2), noise(5, 5, 2))

[[1]]
[1] 2.96407

[[2]]
[1] 1.5710526 0.9691626

[[3]]
[1] 2.802495 4.266730 6.508348

[[4]]
[1] 1.991039 6.221394 2.657954 3.223254

[[5]]
[1] 2.0583406 6.1257683 2.6380365 5.0653189 0.7772871